### PR TITLE
Spc 550 dataloader classes for test train and verify data

### PR DESCRIPTION
**Pull request by saberzero1**

### CODE REVIEW

**Review by GerardvSchie — CHANGES_REQUESTED** [review]
Symlinks look wrong

**Comment by GerardvSchie** [comment]
> Symlinks look wrong

resolved

**Review by GerardvSchie — APPROVED** [review]
symlinks solved

**Review by bacdekker — APPROVED** [review]
Ben het er mee eens

**Review by JTeeuwissen — APPROVED** [review]
I am not going to pretend that I read it all, but yet here we are.

**Pull request merged**
